TITLE = "Bloch Maze"

CELL_SIZE = 50
FONT = 'DejaVu Sans Mono, Segoe UI Symbol'
FONT_SIZE = 23

FPS = 60
MOVE_DELAY = 80
BANNER_DELAY = 500

TITLE_TEXT = "BLOCH MAZE"
CONTROLS_TEXT = "controls:      [w,a,s,d] or [←,↑,↓,→]   "
NAVIGATION_TEXT = "navigation:    [r]eset / [b]ack / [n]ext"
CONTINUE_TEXT = "press <any> key to continue"

SYMBOL_NONE = '.'
SYMBOL_WALL = 'w'
SYMBOL_ENTRANCE = 'A'
SYMBOL_EXIT = 'B'
SYMBOL_X_GATE = 'X'
SYMBOL_Y_GATE = 'Y'
SYMBOL_Z_GATE = 'Z'
SYMBOL_H_GATE = 'H'
SYMBOL_S_GATE = 'S'
SYMBOL_RESET_0_GATE = '0'
SYMBOL_RESET_1_GATE = '1'

STATE_SYMBOL_ZERO = '❘0❭'
STATE_SYMBOL_ONE = '❘1❭'
STATE_SYMBOL_PLUS = '❘+❭'
STATE_SYMBOL_MINUS = '❘-❭'
STATE_SYMBOL_Y_PLUS = '❘y+❭'
STATE_SYMBOL_Y_MINUS = '❘y-❭'

CELL_COLOR_NONE = (255, 255, 255)
CELL_COLOR_WALL = (100, 100, 100)
CELL_COLOR_ENTRANCE = (50, 205, 50)
CELL_COLOR_EXIT = (255, 49, 49)
CELL_COLOR_X_GATE = (0, 170, 255)
CELL_COLOR_Y_GATE = (0, 204, 102)
CELL_COLOR_Z_GATE = (255, 102, 102)
CELL_COLOR_H_GATE = (255, 153, 0)
CELL_COLOR_S_GATE = (204, 153, 255)
CELL_COLOR_RESET_0_GATE = (130, 130, 130)
CELL_COLOR_RESET_1_GATE = (130, 130, 130)
