from maze import Maze, str_to_array
from state import State


class Level:
    def __init__(self, title, subtitle, start_state, end_state, maze):
        self.title = title
        self.subtitle = subtitle
        self.maze = maze
        self.start_state = start_state
        self.end_state = end_state


levels = [
    Level('level 0', "warm-up", State.ZERO, State.PLUS, Maze(str_to_array("""
    ...................
    ...................
    ...................
    ....wwwwwwwwww.....
    ....wA...H..Bw.....
    ....wwwwwwwwww.....
    ...................
    ...................
    ...................
    ...................
    """))),
    Level('level 2', "don't push it", State.ZERO, State.ZERO, Maze(str_to_array("""
    ...................
    ...................
    ...................
    ....wwwwwwwwww.....
    ....wA...H..Bw.....
    ....wwww.www.w.....
    .......w.w.w.w.....
    .......w.www.w.....
    .......w.....w.....
    .......wwwwwww.....
    """))),
]
