from enum import Enum

from config import *


class Cell(str, Enum):
    NONE = SYMBOL_NONE
    WALL = SYMBOL_WALL
    ENTRANCE = SYMBOL_ENTRANCE
    EXIT = SYMBOL_EXIT
    X_GATE = SYMBOL_X_GATE
    Y_GATE = SYMBOL_Y_GATE
    Z_GATE = SYMBOL_Z_GATE
    H_GATE = SYMBOL_H_GATE
    S_GATE = SYMBOL_S_GATE
    RESET_0_GATE = SYMBOL_RESET_0_GATE
    RESET_1_GATE = SYMBOL_RESET_1_GATE


CELL_COLORS = {
    Cell.NONE: CELL_COLOR_NONE,
    Cell.WALL: CELL_COLOR_WALL,
    Cell.ENTRANCE: CELL_COLOR_ENTRANCE,
    Cell.EXIT: CELL_COLOR_EXIT,
    Cell.X_GATE: CELL_COLOR_X_GATE,
    Cell.Y_GATE: CELL_COLOR_Y_GATE,
    Cell.Z_GATE: CELL_COLOR_Z_GATE,
    Cell.H_GATE: CELL_COLOR_H_GATE,
    Cell.S_GATE: CELL_COLOR_S_GATE,
    Cell.RESET_0_GATE: CELL_COLOR_RESET_0_GATE,
    Cell.RESET_1_GATE: CELL_COLOR_RESET_1_GATE,
}
